## Задание1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [18]:
x = np.arange( 0, 10 )

In [19]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Задание2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали

In [25]:
y = np.diag(np.arange(2, 40, 15))
y

array([[ 2,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 32]])

In [28]:
sum_diag = 0
i = 0 
for sum_ in y:
    sum_diag += sum_[i]
    i += 1
    
sum_diag

51

## Задание3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [30]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])

In [31]:
b = np.array ([4, 12, -3])

In [32]:
from numpy import linalg

In [33]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [35]:
np.allclose( np.dot(a, linalg.solve(a, b)), b ) # проверяем на верность

True

## Задание4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [74]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [75]:
a = users_stats[0]
b = users_stats[1]
c = users_stats[2]
d = users_stats[3]
e = users_stats[4]
f = users_stats[5]
g = users_stats[6]
h = users_stats[7]
i = users_stats[8]
j = users_stats[9]

In [110]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [121]:
def cosine( n, next_user_stats):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    # длины векторов
    nLength = np.linalg.norm( n )
    next_user_statsLength = np.linalg.norm( next_user_stats )
    
    return np.dot( n, next_user_stats ) / ( nLength * next_user_statsLength )

In [141]:
result = {}
for i, el in list(enumerate(users_stats)):
    res = cosine(next_user_stats,el)
    result.update({i:res})
    similar_user = max(result, key=lambda key: result[key])

print(f'Самый схожий пользователь: {similar_user + 1}')

Самый схожий пользователь: 8
